name: PR to master branch

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Should be more than 1 for codecov to work
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check formating
        run: go fmt ./... && git diff --quiet

      - name: Download dependencies
        run: go get ./...
      - name: Lint via go vet
        run: go vet ./...

      - name: Run build
        run: go build github.com/bragov4ik/yacal/...

      - name: Run tests
        run: go test github.com/bragov4ik/yacal/...
